version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    post_build:
      - echo "--- Copying static files ---"
      - cp -rf _static_html/index.html $READTHEDOCS_OUTPUT/html/index.html
      - cp -rf _static_html/style.css $READTHEDOCS_OUTPUT/html/style.css

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt

formats:
  - htmlzip